In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

1. Import Dataset

2. Encoding Catagorical Data
    > a. Label Encoding the Gender column

    > b. One Hat encoding the geography column
    
3. Spliting The dataset in training and test set

4. Feature Scaling

In [38]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [39]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [40]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [41]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [42]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

## Data Preprocessing

In [43]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [44]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct  = ColumnTransformer(transformers =[
    ('enc', OneHotEncoder(),[1])], remainder ='passthrough')

X = np.array(ct.fit_transform(X))

In [45]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

## Train Test Split

In [46]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2)

In [47]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train  = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## Building ANN

In [48]:
import tensorflow as tf

### Steps : 

1. Initialize the ANN

2. Adding the input layer and the first hiddne layer

3. Adding the second hidden layer

4. Adding Output layer

----
Training

1. Compile teh ANN

2. Training the ANN on the Training Set

------
Make the prediction on single observation

In [50]:
ann = tf.keras.models.Sequential()

In [51]:
#Add input layer and hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#Add hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [52]:
#Output Layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [53]:
#Training

ann.compile(optimizer= 'adam',loss='binary_crossentropy', metrics = ['accuracy'])
#catagorical_crossentropy --> For non binayr classification
#binary_crossentropy --> For binary classification


In [54]:
ann.fit(x=X_train,y=y_train,batch_size=32, epochs=200)

Epoch 1/200
250/250 [==============================] - 1s 2ms/step - loss: 0.5732 - accuracy: 0.7703
Epoch 2/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4659 - accuracy: 0.7964
Epoch 3/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4449 - accuracy: 0.7964
Epoch 4/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4359 - accuracy: 0.7964
Epoch 5/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4297 - accuracy: 0.7964
Epoch 6/200
250/250 [==============================] - 1s 2ms/step - loss: 0.4246 - accuracy: 0.7964
Epoch 7/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4195 - accuracy: 0.7964
Epoch 8/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4124 - accuracy: 0.8036
Epoch 9/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4015 - accuracy: 0.8129
Epoch 10/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3919 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8633
Epoch 82/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8640
Epoch 83/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8646
Epoch 84/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8633
Epoch 85/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8652
Epoch 86/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8645
Epoch 87/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8630
Epoch 88/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8644
Epoch 89/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3336 - accuracy: 0.8640
Epoch 90/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3336 - accuracy: 

250/250 [==============================] - 0s 2ms/step - loss: 0.3316 - accuracy: 0.8636
Epoch 161/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3319 - accuracy: 0.8643
Epoch 162/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.8631
Epoch 163/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3317 - accuracy: 0.8648
Epoch 164/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3319 - accuracy: 0.8648
Epoch 165/200
250/250 [==============================] - 1s 4ms/step - loss: 0.3316 - accuracy: 0.8648
Epoch 166/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3319 - accuracy: 0.8635
Epoch 167/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.8654
Epoch 168/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3317 - accuracy: 0.8640
Epoch 169/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3319 - a

In [58]:
print(ann.predict(sc.transform([[1,0,0,600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5) 

1/1 [==============================] - 0s 32ms/step
[[False]]


In [63]:
#Predict on test set
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5
print(np.concatenate((y_pred,np.expand_dims(y_test,axis=1)),axis=1))
# y_pred.shape, y_test.shape

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Confusion matrix

In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1539   53]
 [ 213  195]]


0.867